language: ruby
services:
  - redis-server
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database www_rails_test;' -U postgres
  - pecl install imagick
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
notifications:
  slack:
    secure: Qi3NqgqqtUb2Sap9LGHphz5achbAOavYke/AgtYgGrrk7qL0EYUmS74quTb4ciWzse/ig4vT5mbBaqLN1hYchK4RUdjBqu9X4VTUsFpHajZ556rXaiws96wbyasvB6/KZrsi/hhJlil7Q1G4SUEJE9Xx3HMBWOtXu0YDMmGhioL50TuPICY+vGLkiYVvvq47YBqHEyW4ZL0PP9rWxA96tPLMwXvK3PjywfZ0yhN0pO9V9d94sCEZ5puTlK6x5Hv6qNJRwLoOwqOGlEExcc0tJ1N/+kRGNAYdJhRILtqNQqybcnfQarezB02CurEmnnSqaSxrcpwA6fgmA18+CaFXF9708c6icb7qe508RruJ7wttfz8HBR/IbnHEvGltd7eKVfH210jlZSBSOcWrrZX5hgAMqKH8sBzLMW8KNUXLgE7iH+C0vlz4RrzNWPL73Kfx4JK3GZwpoW1XB2ssuek65OVwqMXSpsLhLMdc0rwoQgjIAqKKGYrqvNK+438Os4lbsSOyP6OEOM0u2xC4AdoOWWXKTX7kO3hfk249HX5Uih20sBgQ6dqDGeW0tCfdpBe/ocyE+7eQZcVJ5wqbIJtf47qbxyGx/7/D8kR4rN8FJ+9TFz4ysS6C8DRlBIvJvMFd3825ikYIWSVmhrJ4zdTX4zbQe22Mf8LMvBcA8lYLNqE=
env:
  global:
    # CLOUDINARY_URL + ALUMNI_WWW_SHARED_SECRET + MAILGUN_PUBLIC_API_KEY
    secure: "HY6TWkkJSTlAKT0q9pIf20queTQxQq90MOwWJwI1JG4saCESGRtBf+DAHcrfTL5DJf2rh1bFFCgqYRfiIXP/dO6NIhp7ndNcLzMu21djzvI5QG4D2CW7EwOqjgGL1uEipNJjm7MhSlk+J3yj6HlE8h2nkHfN4DZ6qAc1MVH/iyHhxoEqkgV3ilN+IxGbK2cPN239g7lhv4NNRVNvqUSP98INdYmZnsHjPIjzjUmThuHpKCeQ4jFJlk2mW15AlmQoN+U7r6MfMMb3EXn0VyXvU2uQMGc0eEZ8HdcCwWAtDYKxiXJXRlKLL4/6glVz8SifVZ4GSVC71pGqquOvWaW5Vk5QZgvYcu3n1V/uR3DNzmIi0CIz1laGbpxUHg4OCimQOFkHhyiqcxor/m2eymiqPBs/FKU5digY8cRO3yiRQJFf1X6rLborZeLYrf+Uixy56p7dRFMHQuw67BSTxBmC7CYArPTCp3QV2Rk1VYGtfo1r5ngAtrnpzMXigBcb0vIp9OY7WIT935HkdRy7mmBsotq9TUgx1d+k5UwVQnE/ec5ps671osnpesWCv158voYsNi3/ivDVbIFeNguknrBDFvmBg9BBfB7v9g78abdo0RPF30vF3oTjT6WYw5OgwEH1pcEQaqG2IVkvbvqlQNCVJmDwhj8rFsUQCoCW2ZNj2l0="
